# Generated by Django 5.1.2 on 2024-10-31 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField(auto_now_add=True)),
                ('neck_circumference_cm', models.FloatField(blank=True, null=True)),
                ('shoulder_width_cm', models.FloatField(blank=True, null=True)),
                ('chest_bust_circumference_cm', models.FloatField(blank=True, null=True)),
                ('waist_circumference_cm', models.FloatField(blank=True, null=True)),
                ('hip_circumference_cm', models.FloatField(blank=True, null=True)),
                ('arm_length_cm', models.FloatField(blank=True, null=True)),
                ('upper_arm_circumference_cm', models.FloatField(blank=True, null=True)),
                ('wrist_circumference_cm', models.FloatField(blank=True, null=True)),
                ('inseam_length_cm', models.FloatField(blank=True, null=True)),
                ('outseam_length_cm', models.FloatField(blank=True, null=True)),
                ('thigh_circumference_cm', models.FloatField(blank=True, null=True)),
                ('knee_circumference_cm', models.FloatField(blank=True, null=True)),
                ('calf_circumference_cm', models.FloatField(blank=True, null=True)),
                ('ankle_circumference_cm', models.FloatField(blank=True, null=True)),
                ('total_height_cm', models.FloatField(blank=True, null=True)),
                ('bust_point_to_bust_point_cm', models.FloatField(blank=True, null=True)),
                ('bust_point_to_waist_cm', models.FloatField(blank=True, null=True)),
                ('back_waist_length_cm', models.FloatField(blank=True, null=True)),
                ('front_waist_length_cm', models.FloatField(blank=True, null=True)),
                ('underbust_circumference_cm', models.FloatField(blank=True, null=True)),
                ('chest_width_cm', models.FloatField(blank=True, null=True)),
                ('back_width_cm', models.FloatField(blank=True, null=True)),
                ('sleeve_length_cm', models.FloatField(blank=True, null=True)),
                ('crotch_depth_cm', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='tailoring.measurementcategory')),
            ],
        ),
    ]
