# Generated by Django 5.1.2 on 2024-11-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
    ]
