# Generated by Django 5.1.2 on 2024-10-31 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_customuser_customer_id_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customers',
            field=models.ManyToManyField(blank=True, help_text='Customers associated with a tailor.', related_name='tailors', to=settings.AUTH_USER_MODEL),
        ),
    ]
