# Generated by Django 5.1.2 on 2024-11-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_customuser_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='algorand_private_key',
            field=models.TextField(blank=True, help_text='Algorand private key, securely stored.', null=True),
        ),
    ]
